// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD7qOCxx0-UB2GE2BISXBOsXi6xWxprqA',
    appId: '1:1028564296162:web:c5ee00f5b8dc59c51dd9bb',
    messagingSenderId: '1028564296162',
    projectId: 'todo-design-app',
    authDomain: 'todo-design-app.firebaseapp.com',
    storageBucket: 'todo-design-app.appspot.com',
    measurementId: 'G-E4MHQJ74YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaUiZYWlCdkV4RqbC0Wl42XNTS85fUTnI',
    appId: '1:1028564296162:android:a1a7a6701e96c64a1dd9bb',
    messagingSenderId: '1028564296162',
    projectId: 'todo-design-app',
    storageBucket: 'todo-design-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhLIkbA8vl46-FomCie7W1KJv7EhaFbbo',
    appId: '1:1028564296162:ios:75e9bf470a1df8121dd9bb',
    messagingSenderId: '1028564296162',
    projectId: 'todo-design-app',
    storageBucket: 'todo-design-app.appspot.com',
    androidClientId: '1028564296162-2igtditoij86jmhcb7ko6478fn0q63eq.apps.googleusercontent.com',
    iosClientId: '1028564296162-t86uqdpsug4kunggsrkadiv0777uotfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhLIkbA8vl46-FomCie7W1KJv7EhaFbbo',
    appId: '1:1028564296162:ios:75e9bf470a1df8121dd9bb',
    messagingSenderId: '1028564296162',
    projectId: 'todo-design-app',
    storageBucket: 'todo-design-app.appspot.com',
    androidClientId: '1028564296162-2igtditoij86jmhcb7ko6478fn0q63eq.apps.googleusercontent.com',
    iosClientId: '1028564296162-t86uqdpsug4kunggsrkadiv0777uotfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
